"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = function (moduleName, version) {
  return "/**\n * Flowtype definitions for " + moduleName + "\n * Generated by Flowgen from a Typescript Definition\n * Flowgen v" + version + "\n * Author: [Joar Wilk](http://twitter.com/joarwilk)\n * Repo: http://github.com/joarwilk/flowgen\n */\n\n";
};